### ISSUE TITLE
Issue with `packaging` package with latest versions

### ISSUE THREAD

**Issue by TheMatrixMaster** [getzep/zep-python#75]
### Description
I just installed the following packages in a clean conda environment with `python3.8` and I am running into the following error message. It's pretty easy to duplicate.

### Packages
```requirements.txt
tiktoken==0.4.0
zep-python==1.1.0
packaging==23.1
```

### Error Trace
```
zep-seeder  | Traceback (most recent call last):
zep-seeder  |   File "/app/setup.py", line 9, in <module>
zep-seeder  |     client = ZepClient(base_url=zep_api_url)
zep-seeder  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
zep-seeder  |   File "/usr/local/lib/python3.11/site-packages/zep_python/zep_client.py", line 86, in __init__
zep-seeder  |     self._healthcheck(base_url)
zep-seeder  |   File "/usr/local/lib/python3.11/site-packages/zep_python/zep_client.py", line 120, in _healthcheck
zep-seeder  |     zep_server_version = Version(zep_server_version_str.split("-")[0])
zep-seeder  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
zep-seeder  |   File "/usr/local/lib/python3.11/site-packages/packaging/version.py", line 198, in __init__
zep-seeder  |     raise InvalidVersion(f"Invalid version: '{version}'")
zep-seeder  | packaging.version.InvalidVersion: Invalid version: ''
```

**Comment by danielchalef** [comment]
Thanks for reporting. We've just pushed an update to pypi.

**Comment by TheMatrixMaster** [comment]
I'm stil running into the same issue with `zep-python=1.1.1`

```
annotated-types==0.5.0
anyio==4.0.0
certifi==2023.7.22
charset-normalizer==3.2.0
exceptiongroup==1.1.3
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
idna==3.4
packaging==23.1
pydantic==2.3.0
pydantic_core==2.6.3
regex==2023.8.8
requests==2.31.0
sniffio==1.3.0
tiktoken==0.4.0
typing_extensions==4.7.1
urllib3==2.0.4
zep-python==1.1.1
```

```
Traceback (most recent call last):
  File "zep/setup/setup.py", line 9, in <module>
    client = ZepClient(base_url=zep_api_url)
  File "/Users/stephenlu/anaconda3/envs/gpt/lib/python3.8/site-packages/zep_python/zep_client.py", line 86, in __init__
    self._healthcheck(base_url)
  File "/Users/stephenlu/anaconda3/envs/gpt/lib/python3.8/site-packages/zep_python/zep_client.py", line 120, in _healthcheck
    zep_server_version = Version(zep_server_version_str.split("-")[0])
  File "/Users/stephenlu/anaconda3/envs/gpt/lib/python3.8/site-packages/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: ''
```

**Comment by danielchalef** [comment]
What version of Zep server are you running? Can you share the first few lines of the Zep logs?

**Comment by danielchalef** [comment]
I suspect you're using a very old version of Zep and the newer Zep server version handling in this client was not robust to this. I've improved the server version handling in #77 and released v1.1.2. 

I suggest upgrading Zep. We've added a lot more functionality :-)

**Comment by TheMatrixMaster** [comment]
Pulling the newest changes from `zep-server` solved the issue for me. Thanks @danielchalef !

**Comment by danielchalef** [comment]
Great!
